services:
  postgres:
    container_name: postgres
    hostname: local.postgres
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    env_file:
      - ./envs/postgres.env
    # adicionando a persistencia de dados na sua pasta do projeto
    volumes:
      # persistencia da base
      # - ./data/postgres:/bitnami/postgresql
      # executando um SQL na criação do container
      - ./entrypoint/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - docker_dba

networks:
  docker_dba:
    driver: bridge

# volume interno do container (não aparece na pasta do projeto)
# volumes:
#   postgres_data:
#     driver: local
